import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Head from "next/head";
import Jobs from "@/components/Jobs";
import Overlay from "@/components/Overlay";

export default function Home() {
  return (
    <div className="relative pt-7 md:pt-14 pb-16">
      <Overlay />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Hero />
        <Jobs />
      </main>
    </div>
  );
}
